services:
#    neoxygen_app.example:
#        class: Neoxygen\AppBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
  neoxygen.neoclient:
    class: Neoxygen\AppBundle\Service\Neo4jService
