neoxygen_web:
    resource: "@NeoxygenWebBundle/Controller/"
    type:     annotation
    prefix:   /

neoxygen_app:
    resource: "@NeoxygenAppBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"